version: "2.1"

services:
  ledger:
    image: bat-ledger
    build: .
    restart: always
    volumes:
      - ./test/secrets:/etc/kafka/secrets
    environment:
      - "ALLOWED_ADS_TOKENS=78102ca7-454d-4f6c-b74d-4e1e38e7e40b"
      - "ALLOWED_PUBLISHERS_TOKENS=46bcb4b8-ae58-4d74-acdd-27e98026fc68"
      - "ALLOWED_REFERRALS_TOKENS=a819d462-5fbf-40ed-a941-045de57769ca"
      - "ALLOWED_STATS_TOKENS=f9b58f9a-fb23-49eb-a6e2-9715d46f647b"
      - "BAT_ADS_PAYOUT_ADDRESS=fb599883-c30c-4428-91be-ba901e69a0b2"
      - "BAT_EYESHADE_SERVER=http://eyeshade-web:3002"
      - "BAT_POSTGRES_URL=postgres://eyeshade:password@eyeshade-postgres/eyeshade"
      - BAT_RATIOS_TOKEN
      - "BAT_RATIOS_URL=https://ratios.rewards.bravesoftware.com"
      - "BAT_REDIS_URL=redis://eyeshade-redis:6379"
      - "BAT_SETTLEMENT_ADDRESS=6654ecb0-6079-4f6c-ba58-791cc890a561"
      - "DEBUG=${DEBUG-*,-babel,-eslint:*,-mongo:*,mongo:queries}"
      - DYNO
      - "ENABLE_ADS_PAYOUT=1"
      - "ENV=local"
      - "FASTLY_TOKEN_LIST=421b31c3-57ac-4719-a40a-193d998d93c3"
      - FIXIE_URL
      - "FREEZE_SURVEYORS_AGE_DAYS=${FREEZE_SURVEYORS_AGE_DAYS-7}"
      - HOST
      - IP_GRAYLIST
      - "KAFKA_BROKERS=kafka1:19092"
      - "KAFKA_REQUIRED_ACKS=1"
      - "KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt"
      - "KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem"
      - "KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key"
      - "KAFKA_SSL_KEY_PASSWORD=confluent"
      - "NODE_ENV=${NODE_ENV-development}"
      - PORT
      - "RATIOS_TOKEN=${BAT_RATIOS_TOKEN}"
      - "REDIS_URL=${REDIS_URL-redis://eyeshade-redis:6379}"
      - SENTRY_DSN
      - TESTING_COHORTS
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
      - UPHOLD_CLIENT_ID
      - UPHOLD_CLIENT_SECRET
      - "UPHOLD_ENVIRONMENT=sandbox"
      - "PUBLISHERS_URL=http://127.0.0.1:3000"
      - "PUBLISHERS_TOKEN=00000000-0000-4000-0000-000000000000"
