version: "2.1"

services:
  ledger:
    image: bat-ledger
    build: .
    restart: always
    volumes:
      - ./test/secrets:/etc/kafka/secrets
    environment:
      - "ADS_AVAILABLE_LIST=US"
      - "ADS_URL=${ADS_URL-https://ads-serve.bravesoftware.com}"
      - "BAT_BALANCE_SERVER=http://balance-web:3003"
      - "BAT_EYESHADE_SERVER=http://eyeshade-web:3002"
      - "BAT_GRANT_POSTGRES_URL=postgres://grants:password@grant-postgres/grants?sslmode=disable"
      - "BAT_GRANT_SERVER=http://grant-web:3333"
      - "BAT_LEDGER_SERVER=http://ledger-web:3001"
      - "BAT_MONGODB_URI=mongodb://mongo"
      - "BAT_POSTGRES_URL=postgres://eyeshade:password@eyeshade-postgres/eyeshade"
      - "BAT_RATIOS_URL=https://ratios-staging.mercury.basicattentiontoken.org"
      - "BAT_REDEEMER_REDIS_URL=redis://redeemer-redis:6379"
      - "BAT_REDEEMER_SERVER=http://redeemer-web:3333"
      - "BAT_REDIS_URL=redis://redis:6379"
      - "DEBUG=${DEBUG-*,-babel*,-eslint:*,-mongo:*,mongo:queries,-ava}"
      - "ENABLE_ADS_PAYOUT=1"
      - "ENV=local"
      - "FASTLY_TOKEN_LIST=foobarfoobar"
      - "KAFKA_BROKERS=kafka:19092"
      - "KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt"
      - "KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem"
      - "KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key"
      - "KAFKA_SSL_KEY_PASSWORD=confluent"
      - "KAFKA_REQUIRED_ACKS=1"
      - "FREEZE_SURVEYORS_AGE_DAYS=${FREEZE_SURVEYORS_AGE_DAYS-7}"
      - "GRANT_SERVER=http://grant-web:3333"
      - "LEDGER_URL=${LEDGER_URL-http://ledger-web:3001}"
      - "MONGODB_URI=${MONGODB_URI-mongodb://mongo/ledger}"
      - "NODE_ENV=${NODE_ENV-development}"
      - "REDEEMER_REDIS_HOST=${REDEEMER_REDIS_HOST-redeemer-redis}"
      - "REDEEMER_SERVER=${REDEEMER_SERVER-http://redeemer-web:3333}"
      - "REDIS_URL=${REDIS_URL-redis://redis:6379}"
      - ALLOWED_ADS_TOKENS
      - ALLOWED_PUBLISHERS_TOKENS
      - ALLOWED_REFERRALS_TOKENS
      - ALLOWED_STATS_TOKENS
      - BALANCE_CACHE_TTL_S
      - BALANCE_TOKEN
      - BALANCE_URL
      - BAT_ADS_PAYOUT_ADDRESS
      - BAT_FEE_ACCOUNT
      - BAT_RATIOS_TOKEN
      - BAT_SETTLEMENT_ADDRESS
      - BITCOIN_AVERAGE_PUBLIC_KEY
      - BITCOIN_AVERAGE_SECRET_KEY
      - CAPTCHA_TOKEN
      - CAPTCHA_URL
      - COINBASE_WIDGET_CODE
      - DYNO
      - EYESHADE_GITHUB_CLIENT_ID
      - EYESHADE_GITHUB_CLIENT_SECRET
      - EYESHADE_SLACK_CHANNEL
      - EYESHADE_SLACK_ICON_URL
      - FIXIE_URL
      - FORWARD_TO_GRANTS
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_BYE
      - GITHUB_LOGIN_WORLD
      - GITHUB_ORG
      - HOST
      - IP_GRAYLIST
      - LEDGER_GITHUB_CLIENT_ID
      - LEDGER_GITHUB_CLIENT_SECRET
      - LEDGER_SLACK_CHANNEL
      - LEDGER_SLACK_ICON_URL
      - PER_MEMBER_CLAIM_LIMIT
      - PORT
      - PUBLISHERS_TOKEN
      - PUBLISHERS_URL
      - REDEEMER_CARD_ID
      - REDEEMER_TOKEN
      - SENTRY_DSN
      - SLACK_CHANNEL
      - SLACK_ICON_URL
      - SLACK_WEBHOOK
      - TESTING_COHORTS
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
      - UPHOLD_CLIENT_ID
      - UPHOLD_CLIENT_SECRET
      - UPHOLD_DONOR_CARD_ID
      - UPHOLD_ENVIRONMENT
      - VOTING_COHORTS
      - WALLET_COOLDOWN_BYPASS_TOKEN
      - WALLET_COOLDOWN_HRS
      - YOUTUBE_API_KEY
