version: "2.1"

services:
  ledger:
    image: bat-ledger
    build: .
    restart: always
    volumes:
      - ./test/secrets:/etc/kafka/secrets
    environment:
      - "ADS_AVAILABLE_LIST=US"
      - "ADS_URL=${ADS_URL-https://ads-serve.bravesoftware.com}"
      - "ANON_RATE_LIMIT_PER_M=60000"
      - "BAT_BALANCE_SERVER=http://balance-web:3003"
      - "BAT_EYESHADE_SERVER=http://eyeshade-web:3002"
      - "BAT_GRANT_POSTGRES_URL=postgres://grants:password@grant-postgres/grants?sslmode=disable"
      - "BAT_WALLET_MIGRATION_SERVER=http://wallet-migration-web:3333"
      - "WALLET_MIGRATION_SERVER=http://wallet-migration-web:3333"
      - "WALLET_MIGRATION_TOKEN=${WALLET_MIGRATION_TOKEN-98f27f2e-239b-40e9-8f62-bf1a55ea530c}"
      - "BAT_POSTGRES_URL=postgres://eyeshade:password@eyeshade-postgres/eyeshade"
      - "BAT_RATIOS_URL=https://ratios-staging.mercury.basicattentiontoken.org"
      - "BAT_REDEEMER_REDIS_URL=redis://redeemer-redis:6379"
      - "BAT_REDEEMER_SERVER=http://redeemer-web:3333"
      - "BAT_REWARD_SERVER=http://rewards-dev:3333"
      - "BAT_REDIS_URL=redis://redis:6379"
      - "DEBUG=${DEBUG-*,-babel,-eslint:*,-mongo:*,mongo:queries}"
      - "ENABLE_ADS_PAYOUT=1"
      - "ENV=local"
      - "FASTLY_TOKEN_LIST=421b31c3-57ac-4719-a40a-193d998d93c3"
      - "KAFKA_BROKERS=kafka:19092"
      - "KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt"
      - "KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem"
      - "KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key"
      - "KAFKA_SSL_KEY_PASSWORD=confluent"
      - "KAFKA_REQUIRED_ACKS=1"
      - "FEATURE_WALLET=true"
      - "FREEZE_SURVEYORS_AGE_DAYS=${FREEZE_SURVEYORS_AGE_DAYS-7}"
      - "NODE_ENV=${NODE_ENV-development}"
      - "PER_MEMBER_CLAIM_LIMIT=4"
      - "REDEEMER_REDIS_HOST=${REDEEMER_REDIS_HOST-redeemer-redis}"
      - "REDEEMER_SERVER=${REDEEMER_SERVER-http://redeemer-web:3333}"
      - "REWARD_SERVER=http://rewards-dev:3333"
      - "REDIS_URL=${REDIS_URL-redis://redis:6379}"
      - "GRANT_TOKEN=596fde96-cc80-40e5-b81f-a21c81bb101a"
      - "ALLOWED_ADS_TOKENS=78102ca7-454d-4f6c-b74d-4e1e38e7e40b"
      - "GRANT_SIGNATOR_PUBLIC_KEY=bbe028009e744422bfc39b0e226633324d8c5fe0744c87c1018b88a488bc5899"
      - "REDEEMER_SIGNATOR_PUBLIC_KEY=bbe028009e744422bfc39b0e226633324d8c5fe0744c87c1018b88a488bc5899"
      - "GRANT_WALLET_CARD_ID=f042845f-fa62-4022-8117-a476ec583a7b"
      - "REDEEMER_WALLET_CARD_ID=f042845f-fa62-4022-8117-a476ec583a7b"
      - "ALLOWED_PUBLISHERS_TOKENS=46bcb4b8-ae58-4d74-acdd-27e98026fc68"
      - "ALLOWED_REFERRALS_TOKENS=a819d462-5fbf-40ed-a941-045de57769ca"
      - "ALLOWED_STATS_TOKENS=f9b58f9a-fb23-49eb-a6e2-9715d46f647b"
      - "BAT_SETTLEMENT_ADDRESS=6654ecb0-6079-4f6c-ba58-791cc890a561"
      - BALANCE_CACHE_TTL_S
      - BALANCE_TOKEN
      - BALANCE_URL
      - "BAT_ADS_PAYOUT_ADDRESS=fb599883-c30c-4428-91be-ba901e69a0b2"
      - BAT_FEE_ACCOUNT
      - BAT_RATIOS_TOKEN
      - "RATIOS_SERVICE=${BAT_RATIOS_URL}"
      - "RATIOS_TOKEN=${BAT_RATIOS_TOKEN}"
      - BITCOIN_AVERAGE_PUBLIC_KEY
      - BITCOIN_AVERAGE_SECRET_KEY
      - CAPTCHA_TOKEN
      - "CAPTCHA_URL=https://bat-captcha-staging.herokuapp.com"
      - COINBASE_WIDGET_CODE
      - DISABLE_WALLET_TO_GRANTS
      - DYNO
      - EYESHADE_SLACK_CHANNEL
      - EYESHADE_SLACK_ICON_URL
      - FIXIE_URL
      - FORWARD_TO_GRANTS
      - FORWARD_WALLET_TO_GRANTS
      - HOST
      - IP_GRAYLIST
      - PORT
      - PUBLISHERS_TOKEN
      - PUBLISHERS_URL
      - REDEEMER_CARD_ID
      - "REDEEMER_TOKEN=472872c2-80ac-4c44-a27d-ea0c245a5f5b"
      - SENTRY_DSN
      - SLACK_CHANNEL
      - SLACK_ICON_URL
      - SLACK_WEBHOOK
      - GRANT_WALLET_PUBLIC_KEY
      - GRANT_WALLET_PRIVATE_KEY
      - "TESTING_COHORTS=test"
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
      - UPHOLD_CLIENT_ID
      - UPHOLD_CLIENT_SECRET
      - "UPHOLD_DONOR_CARD_ID=6654ecb0-6079-4f6c-ba58-791cc890a561"
      - "UPHOLD_ENVIRONMENT=sandbox"
      - "VOTING_COHORTS=control,grant,test,ads,safetynet"
      - "WALLET_COOLDOWN_BYPASS_TOKEN=fb9dcd45-36f5-4c2d-b511-90fa1f0cadae"
      - "WALLET_COOLDOWN_HRS=24"
      - YOUTUBE_API_KEY
