import { serial as test } from 'ava'
import uuidV4 from 'uuid/v4'
import {
  timeout
} from 'bat-utils/lib/extras-utils'
import { Runtime } from 'bat-utils'
// import { createDailySnapshot } from '../../eyeshade/workers/snapshots'
import {
  // debug,
  agents,
  ok,
  cleanPgDb
} from '../utils'

const {
  BAT_REDIS_URL,
  BAT_POSTGRES_URL,
  // BAT_RATIOS_URL,
  // BAT_RATIOS_TOKEN,
  TESTING_COHORTS
} = process.env

// const today = new Date('2018-07-30')
const runtime = new Runtime({
  testingCohorts: TESTING_COHORTS ? TESTING_COHORTS.split(',') : [],
  queue: BAT_REDIS_URL,
  prometheus: {
    label: 'eyeshade.worker.1'
  },
  postgres: {
    url: BAT_POSTGRES_URL
  }
})

// const docId = {
//   toString: () => '5b5e55000000000000000000' // 2018-07-30T00:00:00.000Z
// }
// docId.toHexString = docId.toString
// const settlementId = uuidV4().toLowerCase()
// const ownerId = 'publishers#uuid:' + uuidV4().toLowerCase()

// const contributionSettlement = (extras) => Object.assign({
//   probi: '9500000000000000000',
//   fees: '500000000000000000',
//   altcurrency: 'BAT',
//   _id: docId,
//   type: 'contribution',
//   publisher: 'foo.com',
//   owner: ownerId,
//   settlementId: settlementId,
//   address: uuidV4().toLowerCase(),
//   amount: '9.5',
//   currency: 'BAT'
// }, extras)

test.afterEach.always(cleanPgDb(runtime.postgres))

test('check snapshots auth', async (t) => {
  t.plan(0)
  await createSnapshot({
    expect: 403,
    agent: agents.eyeshade.global
  })
  await createSnapshot({
    expect: ok
  })
})
test('duplicate snapshots id posting conficts', async (t) => {
  t.plan(0)
  const { snapshotId } = await createSnapshot({
    expect: ok
  })
  await createSnapshot({
    snapshotId,
    expect: 409
  })
})
test('snapshots getting statuses', async (t) => {
  t.plan(0)
  const snapshotId = uuidV4().toLowerCase()
  await getSnapshot({
    snapshotId,
    expect: 404
  })
  await createSnapshot({
    snapshotId,
    expect: ok
  })
  await getSnapshot({
    snapshotId,
    expect: 202
  })
  let rows = []
  while (!rows.length) {
    await timeout(1000)
    ;({ rows } = await runtime.postgres.query('select * from balance_snapshots where completed = true'))
  }
  await getSnapshot({
    snapshotId,
    expect: ok
  })
})
// test('snapshots are autogenerated by a daily run handler', async (t) => {
//   t.plan(0)
//   const client = await runtime.postgres.connect()
//   const date = justDate(new Date())
//   const result = await createDailySnapshot(debug, runtime, date)
//   const id =
//   t.deepEqual({
//     id,
//     count: 0,
//     completed: true
//   }, _.pick(result[0]))

//   await insertFromSettlement(runtime, client, referralSettlement)

//   await insertFromSettlement(runtime, client, referralSettlement)
// })

async function getSnapshot ({
  snapshotId,
  agent = agents.eyeshade.publishers,
  expect = ok
}) {
  const id = snapshotId || uuidV4().toLowerCase()
  const url = `/v1/snapshots/${id}`
  const { body } = await agent
    .get(url)
    .expect(expect)
  return body
}

async function createSnapshot ({
  snapshotId,
  agent = agents.eyeshade.publishers,
  expect = ok
}) {
  const url = '/v1/snapshots/'
  const payload = {
    snapshotId: snapshotId || uuidV4().toLowerCase()
  }
  const { body } = await agent
    .post(url)
    .send(payload)
    .expect(expect)
  return body
}
